version: '3.3'

services:
  nfs:
    image: itsthenetwork/nfs-server-alpine:12
    container_name: nfs
    restart: unless-stopped
    privileged: true
    environment:
      - SHARED_DIRECTORY=/mnt/share
    volumes:
      - /mnt/share:/mnt/share
    ports:
      - 2049:2049
      - 2049:2049/udp
      - 111:111
      - 111:111/udp
      - 32765:32765
      - 32765:32765/udp
      - 32767:32767
      - 32767:32767/udp
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager] 
 