# Initial parameters
numworkers = 2
vmmemory = 1024
numcpu = 2

instances = []

(1..numworkers).each do |n| 
  instances.push({:name => "worker#{n}", :ip => "192.168.10.#{n+2}"})
end

manager_ip = "192.168.10.2"

File.open("./hosts", 'w') { |file| 
  instances.each do |i|
    file.write("#{i[:ip]} #{i[:name]} #{i[:name]}\n")
  end
}

Vagrant.require_version ">= 1.8.4"

Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |v|
        v.memory = vmmemory
    v.cpus = numcpu
    end

    config.vm.define "manager" do |i|
      i.vm.box = "ubuntu/focal64"
      i.vm.hostname = "manager"
      i.vm.network "forwarded_port", guest: 80, host: 10080
	  i.vm.network "forwarded_port", guest: 888, host: 10888
	  i.vm.network "forwarded_port", guest: 8080, host: 18080
      i.vm.network "forwarded_port", guest: 9443, host: 19443
      i.vm.network "private_network", ip: "#{manager_ip}"
      i.vm.provision :docker
      i.vm.provision :docker_compose
      if File.file?("./hosts") 
        i.vm.provision "file", source: "hosts", destination: "/tmp/hosts"
        i.vm.provision "shell", inline: "cat /tmp/hosts >> /etc/hosts", privileged: true
      end 
	  i.vm.provision "shell", inline: <<-SHELL
	    apt-get update
	    apt-get install -y nfs-common
	  SHELL
      i.vm.provision "shell", inline: "docker swarm init --advertise-addr #{manager_ip}"
      i.vm.provision "shell", inline: "docker swarm join-token -q worker > /vagrant/token"
    end

  instances.each do |instance| 
    config.vm.define instance[:name] do |i|
      i.vm.box = "ubuntu/focal64"
      i.vm.hostname = instance[:name]
      i.vm.network "private_network", ip: "#{instance[:ip]}"
      i.vm.provision :docker
      if File.file?("./hosts") 
        i.vm.provision "file", source: "hosts", destination: "/tmp/hosts"
        i.vm.provision "shell", inline: "cat /tmp/hosts >> /etc/hosts", privileged: true
      end 
	  i.vm.provision "shell", inline: <<-SHELL
	    apt-get update
	    apt-get install -y nfs-common
	  SHELL
      i.vm.provision "shell", inline: "docker swarm join --advertise-addr #{instance[:ip]} --listen-addr #{instance[:ip]}:2377 --token `cat /vagrant/token` #{manager_ip}:2377"
    end 
  end
end